name: flatland-baseline-gpu-env
dependencies:
    - python=3.7
    - tensorflow-gpu=2.1.0
    - pip=20.0
    - pip:
        - flatland-rl==2.2.1
        - CairoSVG==2.4.2
        - pyhumps==1.3.1
        - gputil==1.4.0
        - pyhumps==1.3.1
        - wandb==0.9.2
        - ray[rllib]==0.8.5